# Generated by Django 5.2.4 on 2025-07-28 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
                ('total_lect_now', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DayWiseLec',
            fields=[
                ('dwlid', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=15)),
                ('lec_count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('drid', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=15)),
                ('day_count', models.IntegerField()),
                ('day_lec_count', models.IntegerField()),
                ('attended_count', models.IntegerField()),
                ('not_attended_count', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRecord',
            fields=[
                ('dailyrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.dailyrecord')),
                ('wrid', models.BigAutoField(primary_key=True, serialize=False)),
                ('week_count', models.IntegerField()),
                ('overall_attendance_perc', models.CharField(max_length=10)),
                ('week_total_lec', models.IntegerField()),
                ('attended_total_count', models.IntegerField()),
                ('userw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.dailyrecord',),
        ),
    ]
