# Generated by Django 5.2.4 on 2025-07-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('did', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
            ],
        ),
    ]
