# Generated by Django 5.2.4 on 2025-08-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dailyrecord_day_alter_daywiselec_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='dailyrecord_ptr',
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='overall_attendance_perc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
