# Generated by Django 5.2.4 on 2025-08-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_weeklyrecord_dailyrecord_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyRecord',
        ),
    ]
