# Generated by Django 5.2.4 on 2025-08-01 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_weeklyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRecord',
            fields=[
                ('wrid', models.BigAutoField(primary_key=True, serialize=False)),
                ('week_count', models.IntegerField()),
                ('overall_attendance_perc', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('week_total_lec', models.IntegerField()),
                ('attended_total_count', models.IntegerField()),
                ('userw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
