# Generated by Django 5.2.4 on 2025-08-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_weeklyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyrecord',
            name='attended_total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='week_total_lec',
            field=models.IntegerField(default=0),
        ),
    ]
