# Generated by Django 5.2.4 on 2025-08-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_holidayforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayforecast',
            name='projected_attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
